In [1]:
import joblib
import numpy as np
import pandas as pd
from glob import glob

In [2]:
model = joblib.load("Machine_SVC.pkl")
model

SVC(C=1000.0)

In [3]:
# 導入 SVC 分類器
from sklearn.svm import SVC

# 導入指標以計算準確性
from sklearn.metrics import accuracy_score

In [12]:
df = pd.read_csv("Result_16N.csv", encoding='utf-8')

df.loc[df["ROE_5Y"] >= 5, 'ROE_5YF' ] = '1'
df.loc[df["ROE_5Y"] < 5, 'ROE_5YF' ] = '0'

df.loc[df["EPS_5Y"] >= 0, 'EPS_5YF' ] = '1'
df.loc[df["EPS_5Y"] < 0, 'EPS_5YF' ] = '0' 
    
df.loc[df["毛利率_5Y"] >= 20, '毛利率_5YF' ] = '1'
df.loc[df["毛利率_5Y"] < 20, '毛利率_5YF' ] = '0'

df.loc[df["現金殖利率"] >= 5, '現金殖利率_F' ] = '1'
df.loc[df["現金殖利率"] < 5, '現金殖利率_F' ] = '0'

df.loc[df["成交價"] < 80, '股價_F' ] = '1'
df.loc[df["成交價"] >= 80, '股價_F' ] = '0'

df.loc[df["董監持股"] >= 10, '董監持股_F' ] = '1'
df.loc[df["董監持股"] < 10, '董監持股_F' ] = '0'

df.fillna(0)

df.to_csv("Result_16N.csv", encoding="utf_8_sig", index = False)

In [13]:
df = pd.read_csv("Result_16N.csv", encoding='utf-8')

df.loc[df["Sum"] >= 4, '判斷' ] = '1'
df.loc[df["Sum"] < 4, '判斷' ] = '0'

df.to_csv("Result_16N.csv", encoding="utf_8_sig", index = False)

In [5]:
df = pd.read_csv('Result_16N.csv', index_col=[0, 1], encoding='utf_8_sig')

df

,,ROE_5Y,EPS_5Y,毛利率_5Y,現金股利,成交價,董監持股,現金殖利率,ROE_5YF,EPS_5YF,毛利率_5YF,現金殖利率_F,股價_F,董監持股_F,Sum,判斷
代碼,股票,,,,,,,,,,,,,,,
1101,台泥,10.26,3.37,25.68,2.34,34.25,8.38,6.83,1,1,1,1,1,0,5,1
1102,亞泥,8.44,3.36,22.76,2.77,40.00,27.37,6.93,1,1,1,1,1,1,6,1
1103,嘉泥,4.67,1.46,6.77,0.91,17.05,17.15,5.34,0,1,0,1,1,1,4,1
1104,環泥,7.57,2.02,13.30,1.04,20.45,24.16,5.09,1,1,0,1,1,1,5,1
1108,幸福,1.89,0.23,8.91,0.58,10.35,3.95,5.60,0,1,0,1,1,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9944,新麗,1.38,0.27,23.48,0.60,20.10,26.69,2.99,0,1,1,0,1,1,4,1
9945,潤泰新,19.79,7.05,23.39,1.60,53.60,27.81,2.99,1,1,1,0,1,1,5,1
9946,三發地產,10.59,2.02,33.76,0.50,12.25,0.00,4.08,1,1,1,0,1,0,4,1
9955,佳龍,-6.34,-1.15,0.32,0.80,18.20,39.16,4.40,0,0,0,0,1,1,2,0
9958,世紀鋼,5.95,1.60,14.84,1.51,66.00,18.91,2.29,1,1,0,0,1,1,4,1

In [6]:
df = pd.read_csv('Result_16N.csv', index_col=[0, 1], encoding='utf_8_sig')

X = df.drop(["現金股利", "ROE_5YF", "EPS_5YF", "毛利率_5YF", "現金殖利率_F", "股價_F", "董監持股_F", "Sum", "判斷"], axis=1)

X

           ROE_5Y  EPS_5Y  毛利率_5Y    成交價   董監持股  現金殖利率
代碼   股票
1101 台泥     10.26    3.37   25.68  34.25   8.38   6.83
1102 亞泥      8.44    3.36   22.76  40.00  27.37   6.93
1103 嘉泥      4.67    1.46    6.77  17.05  17.15   5.34
1104 環泥      7.57    2.02   13.30  20.45  24.16   5.09
1108 幸福      1.89    0.23    8.91  10.35   3.95   5.60
...           ...     ...     ...    ...    ...    ...
9944 新麗      1.38    0.27   23.48  20.10  26.69   2.99
9945 潤泰新    19.79    7.05   23.39  53.60  27.81   2.99
9946 三發地產   10.59    2.02   33.76  12.25   0.00   4.08
9955 佳龍     -6.34   -1.15    0.32  18.20  39.16   4.40
9958 世紀鋼     5.95    1.60   14.84  66.00  18.91   2.29

[925 rows x 6 columns]

In [7]:
df = pd.read_csv('Result_16N.csv', index_col=[0, 1], encoding='utf_8_sig')

y = df['判斷']

y

代碼    股票
1101  台泥      1
1102  亞泥      1
1103  嘉泥      1
1104  環泥      1
1108  幸福      0
             ..
9944  新麗      1
9945  潤泰新     1
9946  三發地產    1
9955  佳龍      0
9958  世紀鋼     1
Name: 判斷, Length: 925, dtype: int64

In [8]:
df = pd.read_csv('Result_16N.csv', index_col=[0, 1], encoding='utf_8_sig')

X = df.drop(["現金股利", "ROE_5YF", "EPS_5YF", "毛利率_5YF", "現金殖利率_F", "股價_F", "董監持股_F", "Sum", "判斷"], axis=1)

y = df['判斷']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

model.fit(X_train, y_train)

y_pred=model.predict(X_test)

print('Model accuracy score with rbf kernel and C=1000.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with rbf kernel and C=1000.0 : 0.8865

In [9]:
Data = pd.DataFrame(y_pred)
Data.columns = ["答案"]
Data.to_csv("Answer.csv", index=False, encoding='utf_8_sig')
Data

     答案
0     1
1     1
2     1
3     1
4     0
..   ..
180   0
181   1
182   1
183   1
184   0

[185 rows x 1 columns]

In [17]:
Data = pd.DataFrame(X_test)
Data.to_csv("Answer_Data.csv", encoding='utf_8_sig')
Data

            ROE_5Y  EPS_5Y  毛利率_5Y    成交價   董監持股  現金殖利率
代碼   股票
2385 群光      18.00    6.53   17.10  84.00  10.47   6.13
2450 神腦      10.41    2.44   11.92  30.00  33.53   6.37
4807 日成-KY   17.13    2.64   25.42  19.50  43.00  12.46
9931 欣高      10.25    1.84   17.79  38.50  24.83   2.96
6573 虹揚-KY    1.81    0.54   14.60  13.70   1.99   1.82
...            ...     ...     ...    ...    ...    ...
2367 燿華       1.72    0.30   11.69  19.55   7.56   2.97
9938 百和      15.89    5.07   37.63  57.60   7.42   5.24
1103 嘉泥       4.67    1.46    6.77  17.05  17.15   5.34
2545 皇翔       8.99    2.93   34.60  40.75  45.04   7.51
5521 工信       2.23    0.25    6.35   6.74   3.82   4.45

[185 rows x 6 columns]

In [19]:
File1 = pd.read_csv("Answer.csv")
File2 = pd.read_csv("Answer_Data.csv")

Result = pd.concat([File2, File1], axis=1, sort=False)
Result.to_csv("Answer.csv", index=False, encoding='utf_8_sig')
Result

       代碼     股票  ROE_5Y  EPS_5Y  毛利率_5Y    成交價   董監持股  現金殖利率  答案
0    2385     群光   18.00    6.53   17.10  84.00  10.47   6.13   1
1    2450     神腦   10.41    2.44   11.92  30.00  33.53   6.37   1
2    4807  日成-KY   17.13    2.64   25.42  19.50  43.00  12.46   1
3    9931     欣高   10.25    1.84   17.79  38.50  24.83   2.96   1
4    6573  虹揚-KY    1.81    0.54   14.60  13.70   1.99   1.82   0
..    ...    ...     ...     ...     ...    ...    ...    ...  ..
180  2367     燿華    1.72    0.30   11.69  19.55   7.56   2.97   0
181  9938     百和   15.89    5.07   37.63  57.60   7.42   5.24   1
182  1103     嘉泥    4.67    1.46    6.77  17.05  17.15   5.34   1
183  2545     皇翔    8.99    2.93   34.60  40.75  45.04   7.51   1
184  5521     工信    2.23    0.25    6.35   6.74   3.82   4.45   0

[185 rows x 9 columns]

In [20]:
df = pd.read_csv("Answer.csv", index_col=[0, 1], encoding='utf_8_sig')

df.to_csv("Answer.csv", encoding='utf_8_sig')
df

            ROE_5Y  EPS_5Y  毛利率_5Y    成交價   董監持股  現金殖利率  答案
代碼   股票
2385 群光      18.00    6.53   17.10  84.00  10.47   6.13   1
2450 神腦      10.41    2.44   11.92  30.00  33.53   6.37   1
4807 日成-KY   17.13    2.64   25.42  19.50  43.00  12.46   1
9931 欣高      10.25    1.84   17.79  38.50  24.83   2.96   1
6573 虹揚-KY    1.81    0.54   14.60  13.70   1.99   1.82   0
...            ...     ...     ...    ...    ...    ...  ..
2367 燿華       1.72    0.30   11.69  19.55   7.56   2.97   0
9938 百和      15.89    5.07   37.63  57.60   7.42   5.24   1
1103 嘉泥       4.67    1.46    6.77  17.05  17.15   5.34   1
2545 皇翔       8.99    2.93   34.60  40.75  45.04   7.51   1
5521 工信       2.23    0.25    6.35   6.74   3.82   4.45   0

[185 rows x 7 columns]

In [21]:
df = pd.read_csv("Answer.csv", encoding='utf_8_sig')
# df = df.drop_duplicates()

Data = df[df['答案'] == 1]
Data.to_csv("Answer_Data.csv", index=False, encoding='utf_8_sig')
Data

       代碼     股票  ROE_5Y  EPS_5Y  毛利率_5Y    成交價   董監持股  現金殖利率  答案
0    2385     群光   18.00    6.53   17.10  84.00  10.47   6.13   1
1    2450     神腦   10.41    2.44   11.92  30.00  33.53   6.37   1
2    4807  日成-KY   17.13    2.64   25.42  19.50  43.00  12.46   1
3    9931     欣高   10.25    1.84   17.79  38.50  24.83   2.96   1
5    2104   國際中橡    7.38    2.46   24.70  19.65   0.00   3.87   1
..    ...    ...     ...     ...     ...    ...    ...    ...  ..
177  8463    潤泰材    5.63    0.89   12.47  19.65  46.72   3.61   1
179  9940     信義   15.15    2.32   29.68  29.25  32.56   6.50   1
181  9938     百和   15.89    5.07   37.63  57.60   7.42   5.24   1
182  1103     嘉泥    4.67    1.46    6.77  17.05  17.15   5.34   1
183  2545     皇翔    8.99    2.93   34.60  40.75  45.04   7.51   1

[119 rows x 9 columns]

In [22]:
df = pd.read_csv("Answer_Data.csv", encoding='utf_8_sig')
df = df.drop_duplicates()
df.to_csv("Answer_Data.csv", index=False, encoding='utf_8_sig')
df

       代碼     股票  ROE_5Y  EPS_5Y  毛利率_5Y    成交價   董監持股  現金殖利率  答案
0    2385     群光   18.00    6.53   17.10  84.00  10.47   6.13   1
1    2450     神腦   10.41    2.44   11.92  30.00  33.53   6.37   1
2    4807  日成-KY   17.13    2.64   25.42  19.50  43.00  12.46   1
3    9931     欣高   10.25    1.84   17.79  38.50  24.83   2.96   1
4    2104   國際中橡    7.38    2.46   24.70  19.65   0.00   3.87   1
..    ...    ...     ...     ...     ...    ...    ...    ...  ..
114  8463    潤泰材    5.63    0.89   12.47  19.65  46.72   3.61   1
115  9940     信義   15.15    2.32   29.68  29.25  32.56   6.50   1
116  9938     百和   15.89    5.07   37.63  57.60   7.42   5.24   1
117  1103     嘉泥    4.67    1.46    6.77  17.05  17.15   5.34   1
118  2545     皇翔    8.99    2.93   34.60  40.75  45.04   7.51   1

[119 rows x 9 columns]