In [12]:
import numpy as np
import pandas as pd

In [13]:
data = '2.csv'

df = pd.read_csv(data)
df = df[(df.正負樣本 == 1) | (df.正負樣本 == -1)]

In [14]:
df.head()

,代碼,股票,ROE_5Y,EPS_5Y,毛利率_5Y,ROE_2017,ROE_2018,ROE_2019,ROE_2020,ROE_2021,...,董監持股,現金殖利率,ROE_Test,EPS_Test,毛利率_Test,現金殖利率_Test,成交價_Test,董監持股_Test,符合數量,正負樣本
0,1101,台泥,11.00,3.69,26.64,6.88,12.94,12.54,13.10,9.54,...,8.38,6.95,1,1,1,1,1,0,5,1
1,1102,亞泥,9.81,4.05,24.67,4.65,9.77,13.54,11.07,10.01,...,27.37,7.10,0,1,1,1,1,1,5,1
2,1103,嘉泥,5.24,1.65,6.44,5.57,3.83,6.32,7.55,2.94,...,17.15,5.45,0,1,0,1,1,1,4,1
3,1104,環泥,6.66,1.82,14.24,8.28,6.01,6.35,6.83,5.84,...,24.16,5.09,0,1,0,1,1,1,4,1
4,1108,幸福,1.71,0.21,8.77,-2.23,-4.66,1.07,8.74,5.64,...,3.95,5.66,0,1,0,1,1,0,3,-1

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 939 entries, 0 to 938
Data columns (total 37 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   代碼          939 non-null    int64
 1   股票          939 non-null    object
 2   ROE_5Y      939 non-null    float64
 3   EPS_5Y      939 non-null    float64
 4   毛利率_5Y      939 non-null    float64
 5   ROE_2017    939 non-null    float64
 6   ROE_2018    939 non-null    float64
 7   ROE_2019    939 non-null    float64
 8   ROE_2020    939 non-null    float64
 9   ROE_2021    939 non-null    float64
 10  毛利率_2017    939 non-null    float64
 11  毛利率_2018    939 non-null    float64
 12  毛利率_2019    939 non-null    float64
 13  毛利率_2020    939 non-null    float64
 14  毛利率_2021    939 non-null    float64
 15  負債比_2017    939 non-null    float64
 16  負債比_2018    939 non-null    float64
 17  負債比_2019    939 non-null    float64
 18  負債比_2020    939 non-null    float64
 19  負債比_2021    939 non-null    float64
 20  稅後淨利率_2017  939 non-null    float64
 21  稅後淨利率_2018  939 non-null    float64
 22  稅後淨利率_2019  939 non-null    float64
 23  稅後淨利率_2020  939 non-null    float64
 24  稅後淨利率_2021  939 non-null    float64
 25  現金股利        939 non-null    float64
 26  成交價         939 non-null    float64
 27  董監持股        939 non-null    float64
 28  現金殖利率       939 non-null    float64
 29  ROE_Test    939 non-null    int64
 30  EPS_Test    939 non-null    int64
 31  毛利率_Test    939 non-null    int64
 32  現金殖利率_Test  939 non-null    int64
 33  成交價_Test    939 non-null    int64
 34  董監持股_Test   939 non-null    int64
 35  符合數量        939 non-null    int64
 36  正負樣本        939 non-null    int64
dtypes: float64(27), int64(9), object(1)
memory usage: 278.8+ KB

In [16]:
X = df[['ROE_5Y', 'EPS_5Y', '毛利率_5Y', 'ROE_2017', 'ROE_2018',
        'ROE_2019', 'ROE_2020', 'ROE_2021', '毛利率_2017', '毛利率_2018', '毛利率_2019',
        '毛利率_2020', '毛利率_2021', '負債比_2017', '負債比_2018', '負債比_2019', '負債比_2020',
        '負債比_2021', '稅後淨利率_2017', '稅後淨利率_2018', '稅後淨利率_2019', '稅後淨利率_2020',
        '稅後淨利率_2021', '現金股利', '成交價', '董監持股', '現金殖利率']]

X.head()

,ROE_5Y,EPS_5Y,毛利率_5Y,ROE_2017,ROE_2018,ROE_2019,ROE_2020,ROE_2021,毛利率_2017,毛利率_2018,...,負債比_2021,稅後淨利率_2017,稅後淨利率_2018,稅後淨利率_2019,稅後淨利率_2020,稅後淨利率_2021,現金股利,成交價,董監持股,現金殖利率
0,11.00,3.69,26.64,6.88,12.94,12.54,13.10,9.54,19.24,26.96,...,48.91,10.50,18.17,20.73,24.48,19.81,2.34,33.65,8.38,6.95
1,9.81,4.05,24.67,4.65,9.77,13.54,11.07,10.01,15.67,25.57,...,43.14,10.27,17.99,24.90,23.99,19.55,2.77,39.00,27.37,7.10
2,5.24,1.65,6.44,5.57,3.83,6.32,7.55,2.94,13.47,13.79,...,35.62,46.64,36.76,74.77,89.29,33.67,0.91,16.70,17.15,5.45
3,6.66,1.82,14.24,8.28,6.01,6.35,6.83,5.84,12.21,11.94,...,22.76,31.54,21.99,22.81,23.22,18.33,1.04,20.45,24.16,5.09
4,1.71,0.21,8.77,-2.23,-4.66,1.07,8.74,5.64,3.74,1.40,...,42.23,-3.00,-6.05,1.23,8.66,6.96,0.58,10.25,3.95,5.66

In [17]:
y = df['正負樣本']

y.head()

0    1
1    1
2    1
3    1
4   -1
Name: 正負樣本, dtype: int64

In [18]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

y=le.fit_transform(y)

In [19]:
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [20]:
from sklearn.ensemble import AdaBoostClassifier


# Create adaboost classifer object
abc = AdaBoostClassifier(n_estimators=50, learning_rate=1, random_state=0)

# Train Adaboost Classifer
model1 = abc.fit(X_train, y_train)


#Predict the response for test dataset
y_pred = model1.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score

# calculate and print model accuracy
print("AdaBoost Classifier Model Accuracy:", accuracy_score(y_test, y_pred))

AdaBoost Classifier Model Accuracy: 0.9893617021276596

In [22]:
from sklearn.ensemble import AdaBoostClassifier


# import Support Vector Classifier
from sklearn.svm import SVC


# import scikit-learn metrics module for accuracy calculation
from sklearn.metrics import accuracy_score
svc=SVC(probability=True, kernel='linear')


# create adaboost classifer object
abc =AdaBoostClassifier(n_estimators=50, base_estimator=svc,learning_rate=1, random_state=0)


# train adaboost classifer
model2 = abc.fit(X_train, y_train)


# predict the response for test dataset
y_pred = model2.predict(X_test)


# calculate and print model accuracy
print("Model Accuracy with SVC Base Estimator:",accuracy_score(y_test, y_pred))

Model Accuracy with SVC Base Estimator: 0.6205673758865248